### ISSUE TITLE
error！env：Ubuntu18.04

### ISSUE THREAD

**Issue by geek-mr-xie** [hybtoy/ssrrmu#1]
root@ubuntu-s-1vcpu-1gb-sgp1-01:~# sudo wget https://raw.githubusercontent.com/hybtoy/ssrrmu/master/ssrrmu.sh && chmod +x ssrrmu.sh && bash ssrrmu.sh
--2019-07-17 12:48:56--  https://raw.githubusercontent.com/hybtoy/ssrrmu/master/ssrrmu.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.8.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.8.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 77328 (76K) [text/plain]
Saving to: ‘ssrrmu.sh’

ssrrmu.sh                     100%[=================================================>]  75.52K  --.-KB/s    in 0.005s

2019-07-17 12:48:56 (15.6 MB/s) - ‘ssrrmu.sh’ saved [77328/77328]

ssrrmu.sh: line 67: syntax error near unexpected token `('
ssrrmu.sh: line 67: `   [[ ! -e ${Server_Speeder_file} ]] && echo -e "${Error} 没有安装 锐速(Server Speeder)，请检查 !" && exit 1'
root@ubuntu-s-1vcpu-1gb-sgp1-01:~#

**Comment by x0r2d2** [comment]
Solved
