### ISSUE TITLE
libsodium problem

### ISSUE THREAD

**Issue by Kry4tal** [hybtoy/ssrrmu#2]
When use the shell and you choice.4 to get install libsodium automatically. Shell give back the lastest version of libsodium is 1.0.18.But it downloaded 1.0.17 version

libsodium-1.0.17. 100%[==========>]   1.82M  4.61MB/s    in 0.4s    

2019-08-20 22:32:10 (4.61 MB/s) - ‘libsodium-1.0.17.tar.gz’ saved

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by x0r2d2** [comment]
@Kry4tal 
Fixed now. Please check.
